openapi: 3.0.0
info:
  title: voices-test
  version: '1.0'
servers:
  - url: 'http://localhost/api'
paths:
  /misc/testDelay:
    parameters: []
    get:
      summary: Test Delay
      operationId: get-misc-testDelay
      responses:
        '200':
          description: OK
      description: 'Wait for 2 seconds before returning!'
      security: []
      tags:
        - Misc Endpoints
  /users/meh:
    get:
      summary: Your GET endpoint
      tags:
        - Users
      responses: {}
      operationId: get-users-meh
components:
  schemas: {}
  securitySchemes:
    Bearer Key:
      type: http
      scheme: bearer
security:
  - API Key - 1: []
